--- 
title: "Title"
author: "Suthor"
#supervisor: 
site: bookdown::bookdown_site
output: 
  md_document:
    variant: gfm
    toc: TRUE
    toc_depth: 2
#bibliography: library.bib
#citation-style: ../../MendeleyBib/CitationStyles/nature.csl
#citation-style: https://www.zotero.org/styles/elsevier-harvard
documentclass: book
link-citations: true
github-repo: 
description: "This is document walks through the analyses I performed for this research."


---


# Overview

```{css, echo=FALSE}
pre {
  max-height: 300px;
  overflow-y: auto;
}
pre[class] {
  max-height: 100px;
}
```


```{r GlobalOptions, echo=FALSE}
options(bookdown.render.file_scope = FALSE, knitr.duplicate.label = "allow") 
knitr::opts_chunk$set(cache.path = "5_cache/")
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```


```{r setup, include=FALSE, cache=FALSE}
#Set root directory to R project root
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```


```{r echo=FALSE, out.width = '100%'}
library(kableExtra)
library(knitr)
```




# 

## Prepare data

Use `1_code/r_notebooks/path.Rmd`.

```{r child = '1_code/r_notebooks/path.Rmd'}
```



# References


<div id="refs"></div>



